### ISSUE TITLE
objective-c项目，当手机网络波动时，read函数会阻塞住整个循环。

### ISSUE THREAD

**Issue by witchan** [yint-tech/sekiro-samples#1]
![image](https://github.com/yint-tech/sekiro-samples/assets/21255110/d896ffab-7906-4ae0-a416-9c8cd3e070e2)
当client端的网络异常后，read函数会阻塞住整个循环，网络恢复后，read仍然会一直阻塞。

**Comment by witchan** [comment]
#2

**Comment by liguobao** [comment]
这个有可能的，这种死循环模式可能不那么友好~

**Comment by iinti** [comment]
close because of #2
