### ISSUE TITLE
请问我自己用docker建立的一个服务器不能访问接口

### ISSUE THREAD

**Issue by lls2wow** [yint-tech/sekiro-samples#4]
http://127.0.0.1:5612/asyncinvoke?group=gcaca_G&action=lvlvaction&param=testparm

这里asyncinvoke 换成 /business/invoke等网上查到的路径都不能使用 ,服务端使用的你的docker一键搭建的。Xposed里面有指定正确的ip和端口。

**Comment by liguobao** [comment]
请使用[sekiro-compose](https://oss.iinti.cn/sekiro/sekiro-compose.zip) 这个docker-compose 模板完成系统初始化。
安装教程可以参考：https://sekiro.iinti.cn/sekiro-doc/01_manual/4.server_install.html
还不行可以使用 测试服务器https://sekiro.iinti.cn/ 先用起来

**Comment by lls2wow** [comment]
测试服务器已经测试过可以使用的

**Comment by lls2wow** [comment]
好的 感谢，测试服务器测试过是可以用的

**Comment by lls2wow** [comment]
对了 商业版是哪儿购买, 我没找到

**Comment by liguobao** [comment]
官网，加下商务。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: lls2wow ***@***.***&gt;
发送时间: 2023年12月29日 18:17
收件人: yint-tech/sekiro-samples ***@***.***&gt;
抄送: 李国宝 ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [yint-tech/sekiro-samples] 请问我自己用docker建立的一个服务器不能访问接口 (Issue #4)





 
对了 商业版是哪儿购买, 我没找到

**Comment by lls2wow** [comment]
额 请问官网是？

**Comment by liguobao** [comment]
http://iinti.cn/


这里～

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: lls2wow ***@***.***&gt;
发送时间: 2023年12月29日 18:21
收件人: yint-tech/sekiro-samples ***@***.***&gt;
抄送: 李国宝 ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [yint-tech/sekiro-samples] 请问我自己用docker建立的一个服务器不能访问接口 (Issue #4)

**Comment by liguobao** [comment]
参考 [服务安装](https://sekiro.iinti.cn/sekiro-doc/01_manual/4.server_install.html) 文档部署即可。
